FROM tomcat:7-jre7
ARG source=content/

COPY context.xml /usr/local/tomcat/conf

WORKDIR /usr/local/tomcat/webapps
RUN  rm -rf ROOT
COPY itemviewerservice.war .

RUN mv itemviewerservice.war ROOT.war

WORKDIR /usr/local/tomcat/

ENTRYPOINT ["catalina.sh", "run"]