FROM osucass/sbtomcat

WORKDIR /usr/local/tomcat/webapps
RUN  rm -rf ROOT
COPY itemviewerservice.war .

RUN mv itemviewerservice.war ROOT.war

WORKDIR /usr/local/tomcat/

ENTRYPOINT ["catalina.sh", "run"]