FROM tomcat:8.0.45-jre7
ARG source=content/

WORKDIR /usr/local/tomcat/conf
COPY context.xml .

WORKDIR /usr/local/tomcat/webapps
RUN  rm -rf ROOT
COPY itemviewerservice.war .

RUN mv itemviewerservice.war ROOT.war

WORKDIR /usr/local/tomcat/

ENTRYPOINT ["catalina.sh", "run"]